#!bin/bash
if [ $# -ne 1 ]
then
	echo "input must be 1 file name"
	exit 1
fi
if ! [ -f "$1" ]
then
	echo "no such file in this directory"
	exit 1
fi
if ! [ -d $HOME/.trash ]
then
	mkdir $HOME/.trash
fi
if ! [ -e $HOME/.trash.log ]
then
	touch $HOME/.trash.log
fi
trashName=$(date +%s)
ln "$1" "$HOME/.trash/$trashName"
rm "$1"
echo "$PWD/$1:$trashName" >> $HOME/.trash.log
