#!/bin/bash
answer=""
for pid in $(ps uax | awk '{ print $2 }' | sed 1d)
do
	cp /proc/$pid/status status 2>/dev/null
	cp /proc/$pid/sched sched 2>/dev/null
	if [[ -s status ]] && [[ -s sched ]]; then
	ppid=$(grep "PPid" "status" | awk '{ print $2 }')
        runtime=$(grep "sum_exec_runtime" "sched" | awk '{ print $3 }')
        switches=$(grep "nr_switches" "sched" | awk '{ print $3 }')
        art=$(echo $runtime" "$switches | awk '{ print $1 / $2 }')
        answer=$answer$pid" "$ppid" "$art"\n"
	fi
	rm -f status
	rm -f sched
done
echo -e $answer | sort -k2 -n | sed 1d | awk '{ print "PID="$1" PPID="$2" art="$3 }' > answer4
