#!bin/bash
cat answer4 | awk '
BEGIN {
ppid=0;
m=0;
count=0;
} 
{
now=substr($2, 6)
art=substr($3,5)
if ( now == ppid ) 
{
	count=count+1
	m=m+art
}
else
{
	print "Average_Running_Children_of_ParentID=" ppid " is " m/count"\n"
	count=1
	ppid=now
	m=art
}
print $1" "$2" "$3
}' > answer5
