#!/bin/bash
date=$(date '+%d-%m-%Y_%H-%M-%S')
mkdir ~/test && 
{
echo "catalog test was created successfully" >> ~/report 
touch ~/test/$date
}
ping -c 1 www.net_nikogo.ru || echo $date ERROR >> ~/report 
